#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: perflab-ingress
#  namespace: ingress
#  annotations:
#    nginx.org/mergeable-ingress-type: "master"
#spec:
#  ingressClassName: "nginx"
#  rules:
#    - host: "*.perf.msap.io"

