apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: perflab
  namespace: elastic-system
spec:
  version: 8.1.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: perflab