apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elastic-system
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "*.us-east-2.elb.amazonaws.com"
      http:
        paths:
          - path: "/kb"
            pathType: ImplementationSpecific
            backend:
              service:
                name: perflab-kb-http
                port:
                  number: 5601
